[package]
name = "oving_6"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.0"
hex = "0.4.3"
serde = { version = "1.0.154", features = ["derive"] }
serde_json = "1.0.94"
sha1 = "0.10.5"
